version: "3.9"

services:
  db:
    image: postgres:16
    container_name: stocklab-db-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: stocklabpass
      POSTGRES_DB: db_stocklab
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d db_stocklab"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: stocklab-migrate-dev
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: ["migrate"]
    command: [
      "-path=/migrations",
      "-database=postgres://root:stocklabpass@db:5432/db_stocklab?sslmode=disable",
      "up"
    ]
    restart: "no"

volumes:
  postgres_data_dev:
  
