services:
  api:
    image: arrafll/stocklab-go:latest
    container_name: stocklab
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.production
    depends_on:
      - db
      - migrate
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:16
    container_name: stocklab-db
    restart: always
    env_file:
      - .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    container_name: stocklab-migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    entrypoint: ["migrate"]
    command: [
      "-path=/migrations",
      "-database=postgres://root:stocklabpass@db:5432/db_stocklab?sslmode=disable",
      "up"
    ]
    restart: "on-failure"

volumes:
  postgres_data:
