definitions:
  services.AuthLoginData:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
  services.AuthLoginFailResponse:
    properties:
      message:
        example: Invalid credentials
        type: string
      status:
        example: error
        type: string
    type: object
  services.AuthLoginParamRequest:
    properties:
      email:
        example: andrerafli83@gmail.com
        type: string
      password:
        example: password123
        type: string
    type: object
  services.AuthLoginSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/services.AuthLoginData'
      message:
        example: Login successful
        type: string
      status:
        example: success
        type: string
    type: object
  services.ProductResponse:
    properties:
      price:
        example: 29.99
        type: number
      product_id:
        example: 101
        type: integer
      product_name:
        example: Sample Product
        type: string
    type: object
  services.User:
    properties:
      avatar:
        example: base64imagestring
        type: string
      email:
        example: andrerafli83@gmail.com
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Andre
        type: string
      phone:
        example: "081234567890"
        type: string
      role:
        example: staff
        type: string
    type: object
  services.UserCreateData:
    properties:
      avatar:
        example: base64imagestring
        type: string
      email:
        example: andrerafli83@gmail.com
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Andre
        type: string
      phone:
        example: "09999999999"
        type: string
      role:
        example: staff
        type: string
    type: object
  services.UserCreateFailResp:
    properties:
      message:
        example: Invalid credentials
        type: string
      status:
        example: error
        type: string
    type: object
  services.UserCreateSuccessResp:
    properties:
      data:
        $ref: '#/definitions/services.UserCreateData'
      message:
        example: Login successful
        type: string
      status:
        example: success
        type: string
    type: object
  services.UserDeleteFailResp:
    properties:
      message:
        example: Failed to delete user
        type: string
      status:
        example: error
        type: string
    type: object
  services.UserDeleteSuccessResp:
    properties:
      message:
        example: User fetched successfully
        type: string
      status:
        example: success
        type: string
    type: object
  services.UserDetail:
    properties:
      avatar:
        example: base64imagestring
        type: string
      email:
        example: andrerafli83@gmail.com
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Andre
        type: string
      phone:
        example: "081234567890"
        type: string
      role:
        example: staff
        type: string
    type: object
  services.UserDetailFailResp:
    properties:
      message:
        example: Failed to fetch user
        type: string
      status:
        example: error
        type: string
    type: object
  services.UserDetailSuccessResp:
    properties:
      data:
        $ref: '#/definitions/services.UserDetail'
      message:
        example: User fetched successfully
        type: string
      status:
        example: success
        type: string
    type: object
  services.UserListFailResp:
    properties:
      message:
        example: Failed to fetch users
        type: string
      status:
        example: error
        type: string
    type: object
  services.UserListSuccessResp:
    properties:
      data:
        items:
          $ref: '#/definitions/services.User'
        type: array
      message:
        example: Login successful
        type: string
      status:
        example: success
        type: string
    type: object
  services.UserUpdateData:
    properties:
      email:
        example: andrerafli83@gmail.com
        type: string
      id:
        example: 1
        type: integer
    type: object
  services.UserUpdateFailResp:
    properties:
      message:
        example: Invalid credentials
        type: string
      status:
        example: error
        type: string
    type: object
  services.UserUpdateSuccessResp:
    properties:
      data:
        $ref: '#/definitions/services.UserUpdateData'
      message:
        example: Login successful
        type: string
      status:
        example: success
        type: string
    type: object
info:
  contact:
    email: andrerafli83@gmail.com
    name: Andre R
  description: Dokumentasi API StockLab
  license:
    name: dreowsy
  title: StockLab
  version: "1.0"
paths:
  /stocklab-api/v1/login:
    post:
      consumes:
      - application/json
      description: Login to the system
      parameters:
      - description: User login credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/services.AuthLoginParamRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.AuthLoginSuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/services.AuthLoginFailResponse'
      summary: User login
      tags:
      - auth
  /stocklab-api/v1/users:
    get:
      consumes:
      - application/json
      description: Get all users in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.UserListSuccessResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/services.UserListFailResp'
      security:
      - BearerAuth: []
      summary: Get list of users
      tags:
      - users
  /stocklab-api/v1/users/create:
    post:
      consumes:
      - multipart/form-data
      description: Create a new user and upload avatar
      parameters:
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      - description: Phone
        in: formData
        name: phone
        type: string
      - description: Avatar image
        in: formData
        name: avatar
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.UserCreateSuccessResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.UserCreateFailResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/services.UserCreateFailResp'
      security:
      - BearerAuth: []
      summary: Create user with avatar
      tags:
      - users
  /stocklab-api/v1/users/delete/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.UserDeleteSuccessResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.UserDeleteFailResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/services.UserDeleteFailResp'
      security:
      - BearerAuth: []
      summary: Delete a user
      tags:
      - users
  /stocklab-api/v1/users/detail/{id}:
    get:
      consumes:
      - application/json
      description: Get a single user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.UserDetailSuccessResp'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/services.UserDetailFailResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/services.UserDetailFailResp'
      security:
      - BearerAuth: []
      summary: Get detail of a user
      tags:
      - users
  /stocklab-api/v1/users/update/{id}:
    put:
      consumes:
      - multipart/form-data
      description: Update an existing user and optionally upload a new avatar
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Email
        in: formData
        name: email
        type: string
      - description: Password
        in: formData
        name: password
        type: string
      - description: Name
        in: formData
        name: name
        type: string
      - description: Phone
        in: formData
        name: phone
        type: string
      - description: Avatar image
        in: formData
        name: avatar
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.UserUpdateSuccessResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.UserUpdateFailResp'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/services.UserUpdateFailResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/services.UserUpdateFailResp'
      security:
      - BearerAuth: []
      summary: Update user with avatar
      tags:
      - users
  /v1/product/:
    post:
      consumes:
      - application/json
      description: Menampilkan list product
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.ProductResponse'
      summary: Product list
      tags:
      - product
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" JWT
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
