definitions:
  services.AuthLoginData:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
  services.AuthLoginFailResponse:
    properties:
      message:
        example: Invalid credentials
        type: string
      status:
        example: error
        type: string
    type: object
  services.AuthLoginParamRequest:
    properties:
      email:
        example: andrerafli83@gmail.com
        type: string
      password:
        example: password123
        type: string
    type: object
  services.AuthLoginSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/services.AuthLoginData'
      message:
        example: Login successful
        type: string
      status:
        example: success
        type: string
    type: object
  services.ProductResponse:
    properties:
      price:
        example: 29.99
        type: number
      product_id:
        example: 101
        type: integer
      product_name:
        example: Sample Product
        type: string
    type: object
  services.User:
    properties:
      email:
        example: andrerafli83@gmail.com
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Andre
        type: string
      phone:
        example: "081234567890"
        type: string
      role:
        example: staff
        type: string
    type: object
  services.UserCreate:
    properties:
      email:
        type: string
      name:
        example: Andre
        type: string
      password:
        example: password123
        type: string
      phone:
        example: "09999999999"
        type: string
    type: object
  services.UserCreateData:
    properties:
      email:
        example: andrerafli83@gmail.com
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Andre
        type: string
      phone:
        example: "09999999999"
        type: string
      role:
        example: staff
        type: string
    type: object
  services.UserCreateFailResp:
    properties:
      message:
        example: Invalid credentials
        type: string
      status:
        example: error
        type: string
    type: object
  services.UserCreateSuccessResp:
    properties:
      data:
        $ref: '#/definitions/services.UserCreateData'
      message:
        example: Login successful
        type: string
      status:
        example: success
        type: string
    type: object
  services.UserListFailResp:
    properties:
      message:
        example: Failed to fetch users
        type: string
      status:
        example: error
        type: string
    type: object
  services.UserListSuccessResp:
    properties:
      data:
        $ref: '#/definitions/services.User'
      message:
        example: Login successful
        type: string
      status:
        example: success
        type: string
    type: object
info:
  contact:
    email: andrerafli83@gmail.com
    name: Andre R
  description: Dokumentasi API StockLab
  license:
    name: dreowsy
  title: StockLab
  version: "1.0"
paths:
  /stocklab-api/v1/login:
    post:
      consumes:
      - application/json
      description: Login to the system
      parameters:
      - description: User login credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/services.AuthLoginParamRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.AuthLoginSuccessResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/services.AuthLoginFailResponse'
      summary: User login
      tags:
      - auth
  /stocklab-api/v1/users/create:
    post:
      consumes:
      - application/json
      description: Get all users in the system
      parameters:
      - description: Data pengguna
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/services.UserCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/services.UserCreateSuccessResp'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.UserCreateFailResp'
      summary: Get detail of an user
      tags:
      - users
  /stocklab-api/v1/users/list:
    get:
      consumes:
      - application/json
      description: Get all users in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.UserListSuccessResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/services.UserListFailResp'
      security:
      - BearerAuth: []
      summary: Get list of users
      tags:
      - users
  /v1/product/:
    post:
      consumes:
      - application/json
      description: Menampilkan list product
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.ProductResponse'
      summary: Product list
      tags:
      - product
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" JWT
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
